### ISSUE TITLE
Track clicks for sponsorship packages leaflet

### ISSUE THREAD

**Issue by nikosd** [euruko2013/site#16]
Add a custom google analytics event to track clicks on the pdf for the sponsorships.

**Comment by nikosd** [comment]
I will send the patch later today.

**Comment by fotos** [comment]
@nikosd can you provide the tracking code?

**Comment by nikosd** [comment]
It's something like the following on the "click" event of the link:

``` javascript
_gaq.push(['_trackEvent', 'Sponsors', 'Leaflet downloaded']);
```

The only problem that I see with the current setup is that the ga script is being loaded on the footer, aka the _gaq may not be available. Since the ga.js is being loaded async anyway, it should go on the header.
