### ISSUE TITLE
Site is broken in android

### ISSUE THREAD

**Issue by chief** [euruko2013/site#18]

**Comment by fotos** [comment]
@chief provide more info (browser, browser version, device, Android version, what's broken) and preferably a screenshot.

Are we sure this isn't a bug in an arcane browser version of Android? We tested the site on a modern Android phone and it works as advertised.

Might be [related to this report on SO](http://stackoverflow.com/questions/11301084/why-arent-styles-in-hgroup-on-andriod-2-2-displaying).

**Comment by chief** [comment]
@fotos indeed its for old devices, and its related to hgroup
