### ISSUE TITLE
Standalone page for speakers

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#31]

**Comment by avgerin0s** [comment]
Is there any content for this?

**Comment by fotos** [comment]
Unfortunately not right now! You can use Lorem Ipsum and placeholder images (middleman does that) to create the layout. We want to have this ready as a page and then fill it in as the speakers appear. :-)

**Comment by fotos** [comment]
Is it possible to create a partial and reuse it for the main page as well?

**Comment by avgerin0s** [comment]
Well, it's possible, but I don't think it's the best way.

We want some keynote speakers (3-4) in the main page, and this generates a page with all the speakers inside the YML.

It's your choice though.

**Comment by graffic** [comment]
Ok mergin it now :)

**Comment by avgerin0s** [comment]
@fotos Should we ask the speakers to provide us with their bio?

**Comment by avgerin0s** [comment]
After the end of the voting I'll add the data from the speakers (if any).

IMO, in the listing page (/speakers) we should also include the **title** of the speech and in the speaker specific page (/speaker/name) the full description. Any ideas?

**Comment by avgerin0s** [comment]
@fotos How are we going to show speakers pictures? He have not at least 1 for every speaker, plus every picture has its own dimensions. Should we ask the speakers to submit new images or something?

**Comment by fotos** [comment]
@eavgerinos I have finished this task right now. I will create a PR and merge it. Hold on 15 minutes.

**Comment by avgerin0s** [comment]
@fotos okie dokie ;)

**Comment by fotos** [comment]
Closed by #71.
