### ISSUE TITLE
Standalone page for schedule / programme

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#32]

**Comment by stream7** [comment]
We are working on that to add a section on the home page. It will take a few days to have the graphics ready.

**Comment by stream7** [comment]
My friends Nikoletta and Dora prepared this design and I was thinking that it would probably fit OK in the home page unless there is more info you want to include.

![schedule](http://i3.minus.com/jbwNk8aPYVS12Z.jpg)

Is it OK? I could implement this within the next 2 weeks if you want.

**Comment by fotos** [comment]
@stream7 I like it. It doesn't have to be fancy or have graphics on top, but I like the gear next to the date.

Just some rough ideas: it should highlight important events (red) like registration and keynote speakers, it should demote coffee breaks and lunches (grey). I think both dates formats should be the same (both red, not one red and the other grey). I don't like the side by side layout, I guess it's just an artist's impression, right?

One on top of the other does just fine with id's (#day1, #day1-0800) for linking.

I 'd :heart: it if we had an [ics link](http://en.wikipedia.org/wiki/ICalendar) with the schedule.

**Comment by fotos** [comment]
@stream7 one more comment on this... The "Hello & Welcome" placeholder will be the presentation / slot title but what about the detailed description? Just an idea: it could be collapsible and have a _more_ link near the end of the row?

**Comment by damphyr** [comment]
How about a pop-up div that gray's out the background instead of a collapsible section?

**Comment by damphyr** [comment]
And one question: Do you guys have access to the program outline? That way you can use the actual time slots.
If not, let me know.

**Comment by stream7** [comment]
@damphyr We don't. Could you please send it to me somehow.
The description could be a pop-up or we could just link to the cfp website.

**Comment by fotos** [comment]
@stream7 please don't use a pop-up. They are a UX nightmare on mobile and tablet devices and really hard to make them responsive. I suggest you go with the collapsible idea I originally proposed. Much more manageable and user friendly.

Also we are going to copy / paste the description of the speeches from the CFP site. We shouldn't link to the CFP.

**Comment by nikosd** [comment]
:+1: with @fotos

**Comment by stream7** [comment]
OK, will do. When do you need this to be ready? I guess if the schedule is ready you need it ASAP?

**Comment by nikosd** [comment]
As fast as you can would be nice in order to publish it. When do **you** believe you can have it ready? Do you need help? I could pair with you tomorrow, on Saturday or on Sunday (Wednesday and Friday are off).

**Comment by fotos** [comment]
@stream7 I have asked @damphyr to give you access to the [schedule](https://docs.google.com/a/euruko2013.org/spreadsheet/ccc?key=0Alw_M84u2mNtdE90YzJUeXVZVFJuZkpqYUdLZGF1VXc#gid=0).

Unfortunately, as I just realised, we need to fill in the schedule slots with the speakers. I hope we manage to do this today. This is not a top priority but I'd say by the end of the next week (May 20th) it should be ready. If not earlier.

@nikosd I believe your No.1 priority is the Guide. We should make it pretty and presentable ASAP and put it online. The schedule follows suit.

**Comment by stream7** [comment]
I can give it a try tonight and it would probably be ready. Will try to put the data in a yaml file so you don't have to edit html when the schedule is ready.

Also, a few clarifications about the design.
1. You don't want the graphics below the header
2. You do want the gear next to the date (I'm not sure it makes sense without the graphics to be honest)
3. You don't like the side by side layout. That means it should be one table?

**Comment by fotos** [comment]
That's me (personally) speaking but I'll take it upon me...
1. Yes, YAML is a nice idea. There is already one [YAML for the speakers](https://github.com/euruko2013/site/blob/master/data/speakers.yml). I suggest you use it!
2. OK let's keep the graphic since you already put some work into it. Not bad after all.
3. Yes keep the gear next to the date as well.
4. Yes, it should be one table. Actually 2 tables, one on top of the other. I think it will be much more readable, will need less horizontal space, will degrade much more easily to tablet and mobile viewports. Won't be that fancy but nothing on the site is fancy either. I believe we can add other touches to spice it up.

**Comment by stream7** [comment]
The ics link and the talks' descriptions are still pending but otherwise you can view it here https://github.com/stream7/site/tree/schedule
I will probably finish it today or tomorrow.

**Comment by fotos** [comment]
@stream7 we got the final schedule format. You'll find it in the updated [program outline](https://docs.google.com/a/euruko2013.org/spreadsheet/ccc?key=0Alw_M84u2mNtdE90YzJUeXVZVFJuZkpqYUdLZGF1VXc#gid=0) in the **Final Program** tab.

We are working on filling in the speakers in each slot. We 'll have this tomorrow night.

**Comment by fotos** [comment]
OK I checked it out. Awesome work @stream7. Couple of remarks:
1. Can you do this in a standalone page /schedule? (i.e. _source/schedule.html.erb_) Have a look at _speakers.html.erb_. The index page is getting a bit overloaded. We 'll add links to the standalone page from the #speakers section, the speakers page, and the top of the index.
2. I :heart: microdata. They will work much better on the standalone page, since the index page is already an "Event". Also have a look at the **subevent** property to mark each presentation. :wink:
3. Have a look at the color coding I did in the [outline](https://docs.google.com/a/euruko2013.org/spreadsheet/ccc?key=0Alw_M84u2mNtdE90YzJUeXVZVFJuZkpqYUdLZGF1VXc#gid=0). We could make the registration red (prominent) as well.
4. Thanks you for using clean semantic markup and bootstrap! Free responsiveness FTW.
5. Instead of copying title and speaker names, you can use the speaker id in the schedule YAML, as mentioned in the speakers YAML, and grab the title and the speaker name from there. :wink: I will consider writing ActiveYAML! :laughing: 

It's really something and with a bit more work it can be merged. Great stuff!

**Comment by stream7** [comment]
@fotos OK I can do the changes but I probably won't have the time to do it during the weekend. That means Monday evening...

**Comment by fotos** [comment]
@stream7 no rush for this. I'd like to have it in place and just fill it in when we have a proposed schedule. That means that it's perfectly fine if we finish this by the end of this week. I can lend a hand or two if you want.

Thanks again for all your help.

**Comment by vvatikiotis** [comment]
A few comments:
1. Have a schedule link in the header as well. If there's no room, them take something out, your call. Critical imo as questions about this have started.
2. Link the preso to cftp proposal, so ppl can have more info about each preso.

**Comment by fotos** [comment]
Don't reopen this issue please. The schedule is merged and I track the header thingy in a separate issue.

**Comment by vvatikiotis** [comment]
allright. Up to you about point 2. closing.
