### ISSUE TITLE
Standalone page for venue

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#34]

**Comment by jimzarkadas** [comment]
@fotos I can do it if you want :)

**Comment by fotos** [comment]
@nemlah is on it AFAIK.

@nemlah if you don't have time to tackle it can @jimzar pick it up? If you have done an initial design please upload it and @jimzar can slice it and code it. A quick update on this issue would be more than welcomed!

**Comment by jimzarkadas** [comment]
@nemlah Let me know if you there are any news!

**Comment by fotos** [comment]
@jimzar I suggest you go ahead and do it....

**Comment by jimzarkadas** [comment]
I'll finish this tomorrow with @eavgerinos :)

**Comment by jimzarkadas** [comment]
I''l try to finish this page today... Here is a screenshot of what I've built. If you want any changes, let me know!
![venue](https://f.cloud.github.com/assets/1199812/484418/df6e822e-b8d7-11e2-8fd5-f2e851480173.png)

**Comment by fotos** [comment]
@jimzar thanks for the update. The screenshot didn't make it online! Upload it somewhere and post a URL. Off for dinner, will check it out later.

**Comment by jimzarkadas** [comment]
sorry for that :P i updated my comment ;)

**Comment by fotos** [comment]
@jimzar OK that's something!
1. The instructions should be in English. 90% of the delegates are foreigners.
2. Got JS skills? Want to show them off? Here is a great idea. I'd like to click an icon or text next to each section ("instruction on the map") and the map should change and display appropriate information / directions using paths and vectors.
3. We need more photos of the venue. Feel free to use the ones from [this blog post](http://euruko2013.org/blog/2013-04-01-happy-april-fools-day/).

**Comment by jimzarkadas** [comment]
I am going to translate them of course (this was just for the layout) :D I will add some photos too and try to add some interaction with the map.

Thanks for the feedback!

**Comment by fotos** [comment]
Perhaps @pagojo can help you out with the translation?

Thanks for working on this! :smile:

**Comment by jimzarkadas** [comment]
No prob :D

**Comment by avgerin0s** [comment]
@fotos @nikosd I noticed that **guide** does not mention **where one can buy tickets for metro and buses and how much the cost**. Should it be added in the **venue** page where we describe how to get to the venue or in the **guide** page.

Thanks

**Comment by fotos** [comment]
@eavgerinos the guide. And link to the guide from the venue.

**Comment by jimzarkadas** [comment]
@fotos I am thinking to use this plugin http://hpneo.github.io/gmaps/ in order to give visitors the ability to create a custom route...

The problem is that I need an API key fo google maps. Should i use my personal ?

**Comment by fotos** [comment]
@jimzar I just saw the comment about the API key. In the MR you didn't use any (AFAICS). IIRC v3 of Google Maps JS doesn't require a key to function. You (as an engineer) can provide one if you want to monitor map usage. No need in our case.

**Comment by jimzarkadas** [comment]
Ok i didn't use the API so forget that :)

## 

Jim Zarkadas | @jimzar
