### ISSUE TITLE
Standalone pages for guide

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#35]
- Travel & Accommodation
- Transportation
- Sightseeing

etc

**Comment by skliask** [comment]
I can make this one.
But i really need some info about the subject.Can anyone help?

**Comment by nikosd** [comment]
@fotos should be ready to be shipped as v1. Big thanks to all volunteers for writing the content and @eirc for the coding help :)

**Comment by nikosd** [comment]
Guide is live for review: 
- http://euruko2013.org/guide/city-of-athens/
- http://euruko2013.org/guide/travel-information/
- http://euruko2013.org/guide/transportation/
- http://euruko2013.org/guide/sightseeing/

Next are:
- Suggested hotels
- Vacations suggestions (Incrediblue, our suggestions, etc)

**Comment by avgerin0s** [comment]
:+1: 

Btw, I think we should add some info on how to get to the Venue. or it should go to #34 ?

**Comment by nikosd** [comment]
Totally agree and I have it already in mind - or feel free to do it!

:)

**Comment by avgerin0s** [comment]
I'll help @jimzar do it on #34. Maybe it's more appropriate to put it there. Guide should be destination-agnostic :P

**Comment by nikosd** [comment]
It's live!
