### ISSUE TITLE
Standalone page for activities

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#36]

**Comment by avgerin0s** [comment]
Can you provide us with a small description, please?

**Comment by fotos** [comment]
This was a part of:
http://euruko2013.org/guide/sightseeing/
- a small part of other activities we can arrange such as boat trips (includiblue) and other excursions. I have no idea where we are with this thing and if we have material readily available for the site.

@pagojo, @nolamesa and @nikosd might shed some light into this.

**Comment by nikosd** [comment]
As @fotos says, some stuff could get out of "sightseeing" and we are expecting material from incrediblue. Other than that feel free to add your own ideas for activities mostly but not necessarily outside Athens for before/after the conference.

**Comment by avgerin0s** [comment]
There should be massive activities (Like the Party) or individual would-be-nice-to-visit/do suggestions?

**Comment by nikosd** [comment]
Both of them. Actually I forgot the "spouse activities" for which we have no feedback yet.

**Comment by fotos** [comment]
IIRC this was supposed to be mostly about the spouse activities and the activities that you can also do before / after the conference. The party would be a nice addition here (don't forget it's sponsored by GitHub).

**Comment by avgerin0s** [comment]
I would assign this to me but I lack the content :/ Any ideas where I can get some?

**Comment by nikosd** [comment]
I working on the final part which are the spouse activities but I'm still waiting for the final offer/promo code from athenswalkingtours.com.

**Comment by nikosd** [comment]
http://euruko2013.org/guide/side-activities/
