### ISSUE TITLE
Blog display number of comments per post

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#46]

**Comment by tsironis** [comment]
This is powered by Disqus, right?

**Comment by graffic** [comment]
Yep, perhaps they have a CORS api.

**Comment by nikosd** [comment]
It's not done until it's done. @Agis- please close it once the counter is in place with the number :)

**Comment by agis** [comment]
Yes, it was closed automatically from the PR and I forgot to re-open it :)

**Comment by nikosd** [comment]
Yeah, I imagined that :)

Good morning btw!

**Comment by agis** [comment]
Morning bro :smile:
