### ISSUE TITLE
Fix navbar styling in blog

### ISSUE THREAD

**Issue by agis** [euruko2013/site#51]
It should have a different color to distinguish it from the rest of the page.

**Comment by graffic** [comment]
Uhmmm, if you plan to fix this, perhaps its better I accept the bootstrap pull request.

May be I'm wrong, but I feel that blog and other pages should have the "standar" navbar and leave the homepage with the transparent trick.

(Or may be remove the transparent trick)

**Comment by agis** [comment]
@graffic Let's postpone until your PR is merged.
