### ISSUE TITLE
Display supporters underneath sponsors

### ISSUE THREAD

**Issue by nolamesa** [euruko2013/site#60]
Last year's EuRuKo can be used as a template

**Comment by fotos** [comment]
I already gave out this task to a volunteer in the last EuRuKo Hackathon. Thanks for noting here as well.

**Comment by graffic** [comment]
Hmmm so perhaps we should use the "assigned" in the tasks that "someone is doing" in order to avoid someone to accidentally pull the task and work on it.

**Comment by nikosd** [comment]
@graffic :thumbsup:

**Comment by fotos** [comment]
In order to assign it to anybody he / she needs to be part of the project and AFAIK that means administrative access. Dunno if this is really a solution. A simple "I got this" comment post here should suffice.

**Comment by graffic** [comment]
Good for me. "something" is better than "nothing" :thumbsup:

**Comment by damphyr** [comment]
Administrative access is not necessary, but somebody from the admins needs
to create a contributors team and add it to the repo.
V.-

On Sun, Apr 14, 2013 at 1:53 PM, Javier Gonel notifications@github.comwrote:

> Good to me. "something" is better than "nothing" [image: :thumbsup:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/euruko2013/site/issues/60#issuecomment-16349934
> .

## 

http://www.ampelofilosofies.gr

**Comment by fotos** [comment]
I 'll look into it when I get back home. There is already a contributors
team. :-)

**Comment by fotos** [comment]
OK figured it out. You can create a team with pull access and assign issues to them. No need for admin access, not even push access. Will organize it now and send an email so I can add everybody in this team.

**Comment by fotos** [comment]
@sincospi I believe it was you who got this one, right?

**Comment by sincospi** [comment]
Hi. This was assigned to me, yes.
Do we have a document with the supporter names?

**Comment by fotos** [comment]
So far we have only 1 supporter and his name is:

**Stephan Kmper** - Twitter: S_2K

**Comment by nolamesa** [comment]
It is Kämper If i am not mistaken

**Comment by damphyr** [comment]
It's Kämper...and I know him personally!
Somebody remind me to thank him when I see him next!
:D
V.-

On Wed, Apr 17, 2013 at 2:02 PM, nolamesa notifications@github.com wrote:

> It is Kämper If i am not mistaken
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/euruko2013/site/issues/60#issuecomment-16501480
> .

## 

http://www.ampelofilosofies.gr

**Comment by fotos** [comment]
Closed by #64.

@damphyr don't forget to say thanks! :-)
