### ISSUE TITLE
Display supporter companies

### ISSUE THREAD

**Issue by nolamesa** [euruko2013/site#67]
We have promised to display the supporters' companies as well. For example S_2K has `Seaside Testing` in the company name field. Maybe we can ask him if he wants it or not. Moreover we can ask him if the position of the supporters is ok with him (I suggest it goes under sponsors)

**Comment by skliask** [comment]
Here is <a target="_blank" href="https://github.com/skliask/site/commits/supporter_info">my implementation</a> if you want it :)

**Comment by avgerin0s** [comment]
@skliask PR it so we can fetch it.

**Comment by fotos** [comment]
@skliask I merged your commit and did some fixes on top of it.

I, for one, would like to know what `href` represents on an `<i>` element. :stuck_out_tongue:
