### ISSUE TITLE
www.euruko2013.org should redirect to euruko2013.org

### ISSUE THREAD

**Issue by nikosd** [euruko2013/site#7]
It's not a good thing to allow both www an non www with the similar content. @chief can you at @skroutz handle it?

**Comment by chief** [comment]
@nikosd Do you have any suggestion?

**Comment by nikosd** [comment]
What do you mean by 'suggestion'? Do you want the htaccess redirect conditions or in nginx form?

**Comment by chief** [comment]
@nikosd no no , I thought you meant something else, its ok

**Comment by chief** [comment]
done

**Comment by nikosd** [comment]
thx!
