### ISSUE TITLE
Partners page

### ISSUE THREAD

**Issue by vvatikiotis** [euruko2013/site#72]
The title is a bit unclear, but we need a section were our partners wll have a presence. For instance, Vodafone will (most likely) be our Netwrok/Wifi partner, N21 our organising partner,  GitHub our party partner, etc.

This could be a separate page or a section under the Sponsor section, It's up to you where this information is placed.

**Comment by avgerin0s** [comment]
Is there any design (psd) ready?

**Comment by fotos** [comment]
@eavgerinos there is already a commented out section in the homepage. We can either enable this, or do the standalone page for sponsors / partners I originally envisioned.

**Comment by vvatikiotis** [comment]
Is there a ETA on this? Our partners could use a bit of promo too.

**Comment by fotos** [comment]
We don't have one, I was thinking on maybe finishing this up this weekend.

We only have 2 additional sponsors to add right now and neither is in a hurry:
1. GitHub (but they haven't paid their sponsorship yet)
2. CoLab (they are not in a rush generally)

**Comment by vvatikiotis** [comment]
It would be good for their publicity to do this sooner than later. In a
months time, the site's visibility will drop to next to nothing.

Additionally, we have to make a final decision on the issue of Katerina
Michalistanou, which we left of a few days ago.

**Comment by vvatikiotis** [comment]
Can we have an ETA? We can throw more resources if needed, as several conf issues are closing.

**Comment by fotos** [comment]
Closed by 0830a254.
