### ISSUE TITLE
Guide/Sightseeing/Outside Athens - Problem with Firefox

### ISSUE THREAD

**Issue by batig** [euruko2013/site#77]
Thumbnails don't seem to work there. Does it happen to anybody else?
![firefox bug](https://f.cloud.github.com/assets/1343880/488751/db08bbdc-b986-11e2-899b-71406e17ba61.png).

**Comment by stream7** [comment]
yes it's broken on Firefox

**Comment by nikosd** [comment]
@eirc care to help (or anybody else)?

**Comment by leftis** [comment]
@nikosd  @eirc this happens because of float: left unfortunately i don't have enough time to fix it.

.thumbnails > li {
    margin-left: 30px;
}
.thumbnails > li {
    float: left;
    margin-bottom: 20px;
    margin-left: 20px;
}
