### ISSUE TITLE
Heroku blogpost

### ISSUE THREAD

**Issue by vvatikiotis** [euruko2013/site#78]
Heroku just informed us that Matz and Koichi will provide the blogpost. So the text and the authors photos should match. This issue is just a heads up since I don't know how the blogpost-photo mechanism is wired.

**Comment by fotos** [comment]
Sorry, can't do, won't do!

We 'd have to:
1. create rounded images for both speakers (we don't have them, the ones for the mobile are totally different)
2. change the code somewhere (`blog/_authors` partial I think)

Most of the text has been provided by the respective sponsors and none has been "credited" to them. But [this](http://www.euruko2011.org/2011/05/17/meet-the-sponsors-souncloud.html) is [customary](http://www.euruko2012.org/blog.html).

Closing this.
