### ISSUE TITLE
Link to mobile applications

### ISSUE THREAD

**Issue by nikosd** [euruko2013/site#81]
## Android Google PlayStore:

Badge:
https://developer.android.com/images/brand/en_app_rgb_wo_45.png

Html snippet:

```
<a href="https://play.google.com/store/apps/details?id=com.codigia.euruko2013">
  <img alt="Android app on Google Play"
       src="https://developer.android.com/images/brand/en_app_rgb_wo_45.png" />
</a>
```

bigger badge version:
https://developer.android.com/images/brand/en_app_rgb_wo_60.png

Snippet:

```
<a href="https://play.google.com/store/apps/details?id=com.codigia.euruko2013">
  <img alt="Android app on Google Play"
       src="https://developer.android.com/images/brand/en_app_rgb_wo_60.png" />
</a>
```
## Apple AppStore:

```
<a href="https://itunes.apple.com/us/app/euruko-2013/id648956739?ls=1&mt=8" target="itunes_store"style="display:inline-block;overflow:hidden;background:url(http://linkmaker.itunes.apple.com/htmlResources/assets/images/web/linkmaker/badge_appstore-lrg.png) no-repeat;width:135px;height:40px;@media only screen{background-image:url(http://linkmaker.itunes.apple.com/htmlResources/assets/images/web/linkmaker/badge_appstore-lrg.svg);}">
</a>
```

**Comment by avgerin0s** [comment]
Nice :+1:

**Comment by nolamesa** [comment]
You can use the following snippet for the action button:

```
<a href="https://play.google.com/store/apps/details?id=com.codigia.euruko2013">
  <img alt="Android app on Google Play"  src="https://developer.android.com/images/brand/en_app_rgb_wo_45.png" />
</a>
```

**Comment by avgerin0s** [comment]
This should be added in the layout or in a specific page?

**Comment by nolamesa** [comment]
I suggest we add it at the footer

**Comment by avgerin0s** [comment]
The **footer** is not in the layout. :/

**Comment by fotos** [comment]
@eavgerinos @nolamesa there is no footer (as in "there is no spoon"). Why don't we make one? ;-)

**Comment by fotos** [comment]
I made a (mockup) footer and then made it a (CSS) reality. :-)

All that's left is to put the mobile app buttons inside and upload it. Now is the time to say if I missed anything.

![euruko_footer](https://f.cloud.github.com/assets/11336/565567/d6a48ab0-c621-11e2-9f7f-ef37b37b3476.png)

![euruko_footer_coded](https://f.cloud.github.com/assets/11336/565569/dcfdb602-c621-11e2-9b32-d72d9c4c5d84.png)

**Comment by avgerin0s** [comment]
:+1: 

Nice! Just a note, imho the color should be a little bit lighter to make the app buttons a little bit more discrete. :)

**Comment by fotos** [comment]
@eavgerinos you haven't seen my photoshop skills yet. ;-)
