### ISSUE TITLE
Ag. Eirini page with info about the area, the bars, etc.

### ISSUE THREAD

**Issue by fotos** [euruko2013/site#84]
We should create a party page with info about Ag. Eirini square:
- The area / the church
- The bars
- The offers
- How to get there
- The party (sponsored by [Github](http://www.github.com) :heart_eyes:)

**Comment by vvatikiotis** [comment]
Most def.

**Comment by nikosd** [comment]
Halfway there. My sincere apologies for the ugly code.

**Comment by nikosd** [comment]
What's missing:
1. "Lanyard Badge"
2. "Party Coupon"
3. "Party Poster"

and a final review.

**Comment by nikosd** [comment]
And now that I'm thinking about it also the following:
- Newsflash
- Possibly replace "Contact" link on header with "Party"

@fotos are you on it? I'm thinking to take a break.

**Comment by fotos** [comment]
OK on it for the review.

I'll either do it tonight or tomorrow morning depending on how much energy
I've got left.

-fotos
