### ISSUE TITLE
Broken links in last-minute-tips

### ISSUE THREAD

**Issue by avgerin0s** [euruko2013/site#87]
http://euruko2013.org/guide/last-minute-tips/side-activities

http://euruko2013.org/guide/last-minute-tips/vacations

http://euruko2013.org/guide/last-minute-tips/vacations

Remove last-minute-tips prefix

**Comment by fotos** [comment]
PR or it didn't happen! :-)

**Comment by nikosd** [comment]
Incoming in 1'

**Comment by avgerin0s** [comment]
I was fixing it too :P

**Comment by nikosd** [comment]
I deployed it too :P

**Comment by avgerin0s** [comment]
:+1:

**Comment by fotos** [comment]
Thanks! :v:
