### ISSUE TITLE
Add attribution to Wikitravel.org on "guide" pages

### ISSUE THREAD

**Issue by nikosd** [euruko2013/site#88]
We must attribute Wikitravel, especially for the [transportation guide](http://euruko2013.org/guide/transportation/), as it has come to our (and their) attention that content is heavily borrowed from [them](http://wikitravel.org/en/Athens#By_bicycle)

What we must do:
1. Attribute the authors of the content (Not just Wikitravel).
2. Clearly note that the Wikitravel text content as being available under the CC-by-SA 3.0 license, and note the specific copyright for each image.
3. Wikitravel articles are written, edited, and illustrated by readers. The quality improves when readers can fix factual errors, misspellings, or make other improvements. For this reason, we must also link back to the original Wikitravel article, allowing our readers to update it. A link back is an excellent way to ensure proper attribution of the content you are re-using.

Here is a page that explains it in more details: http://wikitravel.org/shared/How_to_re-use_Wikitravel_guides.

**Comment by dark5un** [comment]
+1
